### ISSUE TITLE
pg_dumpall > "template1": FATAL

### ISSUE THREAD

**Issue by saltarob** [walter-arrighetti/ResolveDB_backup#1]
Hi Walter,

thank you for your script. I tried to adjust it for the new PostgreSQL 9.5 on OS X.
But the pg_dumpall gives following failure message:

> pg_dumpall: could not connect to database "template1": FATAL:  password authentication failed for user "postgres"

Any idea what's wrong?

Thank you.
Best Regards

**Comment by chaos-dotcom** [comment]
please see my fork pull request #4 for this fix for this the --database variable now needs to be defined on line 16

**Comment by saltarob** [comment]
Thank you.
